baseurl: ""
url: "https://davesuzuki-hiya.github.io/kanji-tattoo-finder"
title: "Kanji Tattoo Finder"
description: "Find the perfect Kanji character for your tattoo with accurate meaning matches and warnings for negative connotations."

# GitHub Pages settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge 